import "~/styles/globals.css";

import type { Metadata } from "next";

import { roboto, roboto_mono } from "~/assets/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${roboto_mono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
